volumes:
  pg_chillRate:
  influxdb2-data:
  influxdb2-config:

services:
  db_chillrate:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_chillRate:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app_chillrate:
    build: .
    restart: always
    ports:
      - 8099:8099
      - 8080:8080/udp
      - 8081:8081/udp
    init: true
    depends_on:
      - db_chillrate
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_EMAIL=${SPRING_EMAIL}
      - SPRING_EMAIL_PASSWORD=${SPRING_EMAIL_PASSWORD}
      - SPRING_HOST=${SPRING_HOST}
      - SPRING_PORT=${SPRING_PORT}
      - SECRET_KEY=${SECRET_KEY}
  influxdb:
    restart: always
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminAdmin
      - DOCKER_INFLUXDB_INIT_ORG=myApp
      - DOCKER_INFLUXDB_INIT_BUCKET=testBucket
